# Generated by Django 2.1.1 on 2018-10-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('last_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('first_Name', models.CharField(default=None, max_length=30)),
                ('phone_No', models.CharField(default='rinkiya', max_length=30, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('mother_Tongue', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Hi', max_length=2)),
                ('religion', models.CharField(choices=[('Hd', 'Hindi'), ('Be', 'Bengali'), ('En', 'English'), ('Ur', 'Urdu'), ('Pu', 'Punjabi'), ('Te', 'Telugu'), ('Ta', 'Tamil')], default=None, max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
