# Generated by Django 2.1.1 on 2018-10-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_No',
            field=models.CharField(default='rinkiya ', max_length=30, null=True),
        ),
    ]
