# Generated by Django 2.1.1 on 2018-10-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181011_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mother_Tongue',
            field=models.CharField(choices=[('Hd', 'Hindi'), ('Be', 'Bengali'), ('En', 'English'), ('Ur', 'Urdu'), ('Pu', 'Punjabi'), ('Te', 'Telugu'), ('Ta', 'Tamil')], default='Hi', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='religion',
            field=models.CharField(choices=[('Hi', 'Hindu'), ('Mu', 'Muslim'), ('Ch', 'Christian'), ('Si', 'Sikh'), ('Bd', 'Buddhist'), ('No', 'No Religion'), ('Ot', 'Other')], default=None, max_length=2),
        ),
    ]
