# Generated by Django 2.1.1 on 2018-10-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181011_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_Name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
