# Generated by Django 2.1.1 on 2018-10-11 11:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181011_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_Name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_No',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128),
        ),
    ]
